###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /app1
        volumes:
            - './laravel1:/app1'
        environment:
            - MYSQL_ROOT_PASSWORD=Root@123
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=userDocker
            - MYSQL_PASSWORD=User@123
        ports:
            - '64002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app1
        volumes:
            - './laravel1:/app1'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '64000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app1
        volumes:
            - './laravel1:/app1'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
