###############################################################################
#                          Generated on docker.io                          #
###############################################################################
networks:
  network:
    driver: bridge

services:

  redis:
    image: "redis:alpine"
    container_name: "docker-lemp-redis"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  phpmyadmin:
    image: "phpmyadmin"
    container_name: "docker-lemp-phpmyadmin"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    volumes:
      - /sessions
    depends_on:
      - mysql
    networks:
      - network

  mysql:
    image: "mysql:8.0"
    container_name: "docker-lemp-mysql"
    working_dir: /app1
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        DB_BACKUP_PASSWORD: '${DB_BACKUP_PASSWORD}'
        DB_BACKUP_USER: '${DB_BACKUP_USER}'
    ports:
      - "${DB_MYSQL_PORT:-3306}:3306"
    volumes:
      - "./docker/mysql/initdb:/docker-entrypoint-initdb.d"
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/logs:/var/log/mysql"
    networks:
      - network
    healthcheck:
      test:
          - CMD
          - mysqladmin
          - ping
          - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: "docker-lemp-rabbitmq"
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_PORT:-15672}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - "./docker/rabbitmq/data:/var/lib/rabbitmq"
    networks:
      - network
    healthcheck:
        test:
            - CMD
            - rabbitmq-diagnostics
            - -q
            - ping
        retries: 3
        timeout: 5s

  mailpit:
    image: "axllent/mailpit:latest"
    container_name: "docker-lemp-mailpit"
    ports:
      - "${MAILPIT_PORT:-8025}:8025"
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
    networks:
      - network

  db-mssql:
    container_name: "docker-lemp-dbmssql"
    ports:
      - ${DB_MSSQL_PORT}:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Europe/Istanbul   # Set the timezone to Istanbul
    build:
      context: ./docker/mssql/
      dockerfile: Dockerfile
      # args:
      #   - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/mssql/data/:/var/opt/mssql/data
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: "${MSSQL_LIMIT_CPU:-0.5}"
          memory: "${MSSQL_LIMIT_MEMORY:-2000M}"
        # reservations:
          #   cpus: '0.25'
          #   memory: 256M
