###############################################################################
#                          Generated on docker.io                          #
###############################################################################
services:
  redis:
    image: "redis:alpine"
    container_name: "docker-lemp-redis"
    networks:
      - network

  mysql:
    image: "mysql:8.0"
    container_name: "docker-lemp-mysql"
    working_dir: /app1
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "./docker/mysql/initdb:/docker-entrypoint-initdb.d"
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/logs:/var/log/mysql"
    networks:
      - network

  webserver:
    image: "nginx:alpine"
    container_name: "docker-lemp-nginx"
    working_dir: /app1
    volumes:
      - "./admin:/app1"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${WEB_PORT}:80"
    networks:
      - network

  php-fpm-9001:
    build: 
      context: ./docker/php-fpm
      dockerfile: Dockerfile.9001
    container_name: "docker-lemp-php-fpm-9001"
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data
      - PHP_FPM_LISTEN=9001
    working_dir: /app1
    volumes:
      - "./admin:/app1"
      - "./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/99-overrides.ini"
    depends_on:
      - mysql
    networks:
      - network

  php-fpm-9002:
    build: 
      context: ./docker/php-fpm
      dockerfile: Dockerfile.9002
    container_name: "docker-lemp-php-fpm-9002"
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data
      - PHP_FPM_LISTEN=9002
    working_dir: /app1
    volumes:
      - "./chat:/app1"
      - "./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/99-overrides.ini"
    depends_on:
      - mysql
    networks:
      - network

networks:
  network:
    driver: bridge
