###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /app1
        volumes:
            - './admin:/app1'
        environment:
            - MYSQL_ROOT_PASSWORD=Root@123
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=userDocker
            - MYSQL_PASSWORD=User@123
        ports:
            - '64002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app1
        volumes:
            - './admin:/app1'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '64000:80'

    php-fpm:
        build: phpdocker/php-fpm
        environment:
            - PHP_FPM_USER=www-data
            - PHP_FPM_GROUP=www-data
            - PHP_FPM_LISTEN=9000
        working_dir: /app1
        volumes:
            - './admin:/app1'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/99-overrides.ini'
        # command: bash -c "chown -R www-data:www-data /app1"

